# -*- coding: utf-8 -*-
"""Error detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_LMeT7Gkf0pU-fNr1E226rhrqRKnPxw
"""

!pip install --upgrade tensorflow keras fastapi uvicorn python-multipart pyngrok nest-asyncio opencv-python-headless

import nest_asyncio
from pyngrok import ngrok
import uvicorn

from fastapi import (
    FastAPI,
    UploadFile,
    File,
    Form,
    HTTPException
)

from fastapi.middleware.cors import CORSMiddleware

import cv2
import numpy as np
import tensorflow as tf

import tempfile
import os
import base64

ngrok.set_auth_token("YOUR_NGROK_TOKEN")
public_url = ngrok.connect(8000).public_url

print("\n" + "=" * 60)
print("SUCCESS!")
print("=" * 60)

print(
    f"\nPaste this URL into dashboard.html:"
)

print(
    f"fetch('{public_url}/predict', {{ ... }})\n"
)

app = FastAPI()


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


IMG_SIZE = 128

THRESHOLDS = {

    "bottle": 0.0030698007,

    "cable": 0.00556921,

    "capsule": 0.0025267671,

    "screw": 0.0025267671,

    "metal_nut": 0.0025267671
}

MODEL_DIR = "/content"

print("\nLoading models into Colab RAM...")

loaded_models = {}


for category in THRESHOLDS.keys():

    model_path = os.path.join(
        MODEL_DIR,
        f"{category}_defect_autoencoder.keras"
    )

    try:

        loaded_models[category] = (
            tf.keras.models.load_model(
                model_path,
                compile=False
            )
        )

        print(
            f"Loaded {category} successfully."
        )

    except Exception as e:

        print(
            f"Failed to load {category}: {e}"
        )


print(
    f"\nTotal models loaded: "
    f"{len(loaded_models)}"
)


# ============================================================
# PREPROCESS IMAGE
# ============================================================

def preprocess_image(file_path):

    image = cv2.imread(file_path)

    if image is None:

        raise ValueError(
            "Could not read uploaded image."
        )

    image = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2RGB
    )

    image = cv2.resize(
        image,
        (IMG_SIZE, IMG_SIZE)
    )

    image = image.astype(
        "float32"
    ) / 255.0

    # Add batch dimension
    image = np.expand_dims(
        image,
        axis=0
    )

    return image

def calculate_reconstruction_error(
    original,
    reconstructed
):

    error = np.mean(
        np.square(
            original - reconstructed
        ),
        axis=(1, 2, 3)
    )

    return float(error[0])

def create_heatmap(
    original,
    reconstructed
):

    diff = np.abs(
        original[0] -
        reconstructed[0]
    )

    # Convert pixel difference to grayscale
    gray_diff = cv2.cvtColor(
        diff.astype(np.float32),
        cv2.COLOR_RGB2GRAY
    )

    # Normalize safely
    min_value = gray_diff.min()
    max_value = gray_diff.max()

    if max_value > min_value:

        gray_diff = (
            (gray_diff - min_value)
            /
            (max_value - min_value)
            *
            255.0
        )

    else:

        gray_diff = np.zeros_like(
            gray_diff
        )

    gray_diff = gray_diff.astype(
        np.uint8
    )

    # Apply heatmap
    heatmap = cv2.applyColorMap(
        gray_diff,
        cv2.COLORMAP_JET
    )

    success, buffer = cv2.imencode(
        ".jpg",
        heatmap
    )

    if not success:

        raise ValueError(
            "Could not create heatmap."
        )

    heatmap_b64 = base64.b64encode(
        buffer
    ).decode("utf-8")

    return heatmap_b64

@app.post("/predict")
async def predict(
    file: UploadFile = File(...),
    category: str = Form(...)
):

    category = category.lower().strip()


    if category not in loaded_models:

        raise HTTPException(
            status_code=400,
            detail=(
                f"Invalid category: {category}. "
                f"Available categories: "
                f"{list(loaded_models.keys())}"
            )
        )

    with tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".png"
    ) as temp_file:

        temp_file.write(
            await file.read()
        )

        temp_path = temp_file.name


    try:


        image = preprocess_image(
            temp_path
        )


        model = loaded_models[
            category
        ]

        threshold = THRESHOLDS[
            category
        ]

        reconstructed = model.predict(
            image,
            verbose=0
        )


        error = calculate_reconstruction_error(
            image,
            reconstructed
        )



        if error > threshold:

            prediction = "Defective"

        else:

            prediction = "Good"


        heatmap_b64 = create_heatmap(
            image,
            reconstructed
        )


        print("\n" + "-" * 50)

        print(
            f"Category: {category}"
        )

        print(
            f"Reconstruction error: "
            f"{error:.10f}"
        )

        print(
            f"Threshold: "
            f"{threshold:.10f}"
        )

        print(
            f"Prediction: "
            f"{prediction}"
        )


        return {

            "prediction": prediction,

            "category": category,

            "reconstruction_error": error,

            "threshold": threshold,

            "heatmap": heatmap_b64
        }


    finally:

        # ----------------------------------------------------
        # Delete temporary file
        # ----------------------------------------------------

        if os.path.exists(temp_path):

            os.remove(temp_path)


# ============================================================
# START SERVER
# ============================================================

config = uvicorn.Config(
    app,
    host="0.0.0.0",
    port=8000
)

server = uvicorn.Server(
    config
)

await server.serve()

